#ifndef __DC_MOTOR_MODULE_API_H
#define __DC_MOTOR_MODULE_API_H

#include "txm_module.h"

#define DC_MOTOR_MODULE_REQUEST_BASE          0x500u

#define DC_MOTOR_MODULE_REQ_GET_COMMAND_TICK  (DC_MOTOR_MODULE_REQUEST_BASE + 1u)
#define DC_MOTOR_MODULE_REQ_GET_COMMAND_VALID  (DC_MOTOR_MODULE_REQUEST_BASE + 2u)
#define DC_MOTOR_MODULE_REQ_GET_LEFT_COUNTS    (DC_MOTOR_MODULE_REQUEST_BASE + 3u)
#define DC_MOTOR_MODULE_REQ_GET_RIGHT_COUNTS   (DC_MOTOR_MODULE_REQUEST_BASE + 4u)
#define DC_MOTOR_MODULE_REQ_APPLY_PWM         (DC_MOTOR_MODULE_REQUEST_BASE + 5u)
#define DC_MOTOR_MODULE_REQ_DEBUG_LOG         (DC_MOTOR_MODULE_REQUEST_BASE + 6u)

#define DC_MOTOR_MODULE_LOG_RUNNING           1u

#endif
