#ifndef __HEALTH_MODULE_API_H
#define __HEALTH_MODULE_API_H

#include "txm_module.h"

#define HEALTH_MODULE_REQUEST_BASE            0x700u

#define HEALTH_MODULE_REQ_GET_SPEED_AGE_TICKS  (HEALTH_MODULE_REQUEST_BASE + 1u)
#define HEALTH_MODULE_REQ_GET_SENSORS_AGE_TICKS (HEALTH_MODULE_REQUEST_BASE + 2u)
#define HEALTH_MODULE_REQ_GET_ULTRASONIC_AGE_TICKS (HEALTH_MODULE_REQUEST_BASE + 3u)
#define HEALTH_MODULE_REQ_GET_DC_MOTOR_AGE_TICKS (HEALTH_MODULE_REQUEST_BASE + 4u)
#define HEALTH_MODULE_REQ_GET_SERVO_AGE_TICKS   (HEALTH_MODULE_REQUEST_BASE + 5u)
#define HEALTH_MODULE_REQ_DEBUG_LOG             (HEALTH_MODULE_REQUEST_BASE + 6u)

#define HEALTH_MODULE_LOG_RUNNING               1u

#endif
