#ifndef __SENSORS_MODULE_API_H
#define __SENSORS_MODULE_API_H

#include "txm_module.h"

#define SENSORS_MODULE_REQUEST_BASE              0x300u

#define SENSORS_MODULE_REQ_GET_TICKS            (SENSORS_MODULE_REQUEST_BASE + 1u)
#define SENSORS_MODULE_REQ_GET_HTS221_TEMP_X100 (SENSORS_MODULE_REQUEST_BASE + 2u)
#define SENSORS_MODULE_REQ_GET_HTS221_HUM_X100  (SENSORS_MODULE_REQUEST_BASE + 3u)
#define SENSORS_MODULE_REQ_GET_BATTERY_MV       (SENSORS_MODULE_REQUEST_BASE + 4u)
#define SENSORS_MODULE_REQ_GET_BATTERY_PERCENT  (SENSORS_MODULE_REQUEST_BASE + 5u)

#define SENSORS_MODULE_REQ_PUBLISH_HTS221       (SENSORS_MODULE_REQUEST_BASE + 6u)
#define SENSORS_MODULE_REQ_PUBLISH_BATTERY      (SENSORS_MODULE_REQUEST_BASE + 7u)
#define SENSORS_MODULE_REQ_SET_HTS221_INVALID   (SENSORS_MODULE_REQUEST_BASE + 8u)
#define SENSORS_MODULE_REQ_SET_BATTERY_INVALID  (SENSORS_MODULE_REQUEST_BASE + 9u)
#define SENSORS_MODULE_REQ_DEBUG_LOG            (SENSORS_MODULE_REQUEST_BASE + 10u)

#define SENSORS_MODULE_INVALID_SAMPLE           0x7FFFFFFFu
#define SENSORS_MODULE_LOG_RUNNING              1u

#endif