#ifndef __SERVO_MOTOR_MODULE_API_H
#define __SERVO_MOTOR_MODULE_API_H

#include "txm_module.h"

#define SERVO_MOTOR_MODULE_REQUEST_BASE        0x600u

#define SERVO_MOTOR_MODULE_REQ_GET_COMMAND_TICK (SERVO_MOTOR_MODULE_REQUEST_BASE + 1u)
#define SERVO_MOTOR_MODULE_REQ_GET_COMMAND_VALID (SERVO_MOTOR_MODULE_REQUEST_BASE + 2u)
#define SERVO_MOTOR_MODULE_REQ_GET_ANGLE_DEG    (SERVO_MOTOR_MODULE_REQUEST_BASE + 3u)
#define SERVO_MOTOR_MODULE_REQ_APPLY_ANGLE      (SERVO_MOTOR_MODULE_REQUEST_BASE + 4u)
#define SERVO_MOTOR_MODULE_REQ_DEBUG_LOG        (SERVO_MOTOR_MODULE_REQUEST_BASE + 5u)

#define SERVO_MOTOR_MODULE_LOG_RUNNING          1u

#endif
