#ifndef __SPEED_SENSOR_MODULE_API_H
#define __SPEED_SENSOR_MODULE_API_H

#include "txm_module.h"

/* Application request IDs shared by kernel and speed-sensor module. */
#define SPEED_SENSOR_MODULE_REQUEST_BASE            (TXM_APPLICATION_REQUEST_ID_BASE + 0x200)
#define SPEED_SENSOR_MODULE_REQ_GET_ENCODER_COUNT  (SPEED_SENSOR_MODULE_REQUEST_BASE + 1)
#define SPEED_SENSOR_MODULE_REQ_GET_TICKS          (SPEED_SENSOR_MODULE_REQUEST_BASE + 2)
#define SPEED_SENSOR_MODULE_REQ_GET_PWM            (SPEED_SENSOR_MODULE_REQUEST_BASE + 3)
#define SPEED_SENSOR_MODULE_REQ_PUBLISH_SPEED_MMPS (SPEED_SENSOR_MODULE_REQUEST_BASE + 4)
#define SPEED_SENSOR_MODULE_REQ_PUBLISH_GEAR       (SPEED_SENSOR_MODULE_REQUEST_BASE + 5)

#define SPEED_SENSOR_MODULE_GEAR_NEUTRAL           0u
#define SPEED_SENSOR_MODULE_GEAR_REVERSE           1u
#define SPEED_SENSOR_MODULE_GEAR_DRIVE             2u

#endif
