#ifndef __SPEED_SENSOR_MODULE_API_H
#define __SPEED_SENSOR_MODULE_API_H

#include "txm_module.h"

/*
 * Application-defined request IDs shared by kernel and speed-sensor module.
 * ThreadX adds/removes TXM_APPLICATION_REQUEST_ID_BASE internally.
 */
#define SPEED_SENSOR_MODULE_REQUEST_BASE            0x200u
#define SPEED_SENSOR_MODULE_REQ_GET_ENCODER_COUNT  (SPEED_SENSOR_MODULE_REQUEST_BASE + 1u)
#define SPEED_SENSOR_MODULE_REQ_GET_TICKS          (SPEED_SENSOR_MODULE_REQUEST_BASE + 2u)
#define SPEED_SENSOR_MODULE_REQ_GET_PWM            (SPEED_SENSOR_MODULE_REQUEST_BASE + 3u)
#define SPEED_SENSOR_MODULE_REQ_PUBLISH_SPEED_MMPS (SPEED_SENSOR_MODULE_REQUEST_BASE + 4u)
#define SPEED_SENSOR_MODULE_REQ_PUBLISH_GEAR       (SPEED_SENSOR_MODULE_REQUEST_BASE + 5u)
#define SPEED_SENSOR_MODULE_REQ_DEBUG_LOG          (SPEED_SENSOR_MODULE_REQUEST_BASE + 6u)

#define SPEED_SENSOR_MODULE_GEAR_NEUTRAL           0u
#define SPEED_SENSOR_MODULE_GEAR_REVERSE           1u
#define SPEED_SENSOR_MODULE_GEAR_DRIVE             2u

#define SPEED_SENSOR_MODULE_LOG_RUNNING            1u

#endif
