#ifndef __ULTRASONIC_MODULE_API_H
#define __ULTRASONIC_MODULE_API_H

#include "txm_module.h"

#define ULTRASONIC_MODULE_REQUEST_BASE             0x400u

#define ULTRASONIC_MODULE_REQ_INIT                (ULTRASONIC_MODULE_REQUEST_BASE + 1u)
#define ULTRASONIC_MODULE_REQ_GET_TICKS           (ULTRASONIC_MODULE_REQUEST_BASE + 2u)
#define ULTRASONIC_MODULE_REQ_GET_RANGE_CM        (ULTRASONIC_MODULE_REQUEST_BASE + 3u)
#define ULTRASONIC_MODULE_REQ_GET_CURRENT_SPEED_MMPS (ULTRASONIC_MODULE_REQUEST_BASE + 4u)
#define ULTRASONIC_MODULE_REQ_GET_CURRENT_GEAR    (ULTRASONIC_MODULE_REQUEST_BASE + 5u)
#define ULTRASONIC_MODULE_REQ_SET_EMERGENCY_BRAKE (ULTRASONIC_MODULE_REQUEST_BASE + 6u)
#define ULTRASONIC_MODULE_REQ_CLEAR_EMERGENCY_BRAKE (ULTRASONIC_MODULE_REQUEST_BASE + 7u)
#define ULTRASONIC_MODULE_REQ_MOTOR_STOP          (ULTRASONIC_MODULE_REQUEST_BASE + 8u)
#define ULTRASONIC_MODULE_REQ_MOTOR_BACKSPIN      (ULTRASONIC_MODULE_REQUEST_BASE + 9u)
#define ULTRASONIC_MODULE_REQ_DEBUG_LOG           (ULTRASONIC_MODULE_REQUEST_BASE + 10u)

#define ULTRASONIC_MODULE_GEAR_REVERSE            1u

#define ULTRASONIC_MODULE_INVALID_SAMPLE          0x7FFFFFFFu
#define ULTRASONIC_MODULE_LOG_RUNNING             1u

#endif
