name: Sync meta-cross to separate repo

on:
  push:
    branches:
      - fix/sync-meta-cross

permissions:
  contents: write

concurrency:
  group: meta-cross-sync
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "meta-layer bot"
          git config --global user.email "bot@drivapi.com"

      - name: Split meta-cross folder
        run: |
          git subtree split --prefix=meta-cross --branch meta-cross-only || exit 1

      - name: Debug Secret
        run: '[ -z "${{ secrets.META_DRIVAPI_PUSH_TOKEN }}" ] && echo "Secret is missing!" && exit 1 || echo "Secret is set"'

      - name: Push to meta-cross repo
        run: |
          git config --global credential.helper store
          echo "https://x-oauth-basic:${{ secrets.META_DRIVAPI_PUSH_TOKEN }}@github.com" > ~/.git-credentials
          chmod 600 ~/.git-credentials
          git push https://github.com/Zahhask45/meta-drivapi.git meta-cross-only:main --force -v || exit 1
